// Player-facing explanations of every stat and term shown in the interface.
export const GLOSSARY: Record<string, string> = {
  vigor: 'Vigor: maximum health.',
  might: 'Might: damage dealt by each strike. Also adds to a Mender’s healing.',
  guard: 'Guard: subtracted from every hit taken. At least 30% of a hit always gets through.',
  speed: 'Speed: how often a combatant acts. 12 Speed acts 20% more often than 10.',
  ranged: 'Ranged: full damage from the back row, and never misses flying enemies.',
  pierce: 'Pierce: ignores this much of the target’s Guard.',
  light: 'Light: prevents ambushes (including Mistbound ambushes) and negates darkness hazards.',
  carry: 'Carry: extra space in the party’s packs for supplies and loot.',
  ward: 'Ward: reduces damage from road hazards by this percent (max 75%).',
  discovery: 'Discovery: increases the chance of finding sites and secrets on the road.',
  mending: 'Mending: extra healing whenever this wayfarer heals someone.',
  shock: 'Shock: chance per hit to stagger the target, making it lose its next action.',
  danger: 'Danger: how hard the route’s enemies and hazards are, from 1 to 5.',
  intel: 'Intel: how precise your forecasts are. Raised by the Cartographer’s Table and every 10 Scouting levels.',
  hands: 'Hands: camp workers. Each work order needs 1–2; each porter on an expedition takes one.',
  porters: 'Porters: camp hands who carry packs (+8 carry each). They are away until the expedition ends.',
  capacity: 'Carry capacity: 5 per wayfarer, 8 per porter, plus frames and the Depot. Supplies and loot share it.',
  standing: 'Standing: the Compact’s reputation. Earned from contracts, relit waystones and discoveries. Raises your charter rank.',
  marks: 'Marks: the Compact’s currency. Paid by settlements and expeditions; spent on upgrades and supplies.',
  drift: 'The Drift: each reach’s conditions shift every two hours, changing danger and rewards.',
  front: 'Front row: takes melee attacks. Non-ranged weapons hit at full strength.',
  back: 'Back row: safe from melee while anyone stands in front, but ranged and diving enemies can still reach it. Non-ranged weapons deal 70% damage from here.',
  offline: 'Offline limit: progress while the game is closed is counted up to this limit. The Signal Beacon raises it.',
  risk: 'Risk: Careful is slower but safer; Bold is faster and richer but meets more trouble.',
  standingOrders: 'Standing orders: when the run succeeds, the party rests until 90% health and then sets out again with the same supplies, as long as you have them.',
};
